# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

    Genre.create(tmdb_genre_id: 28, name: "Action")
	Genre.create(tmdb_genre_id: 10759, name: "Action & Adventure")
    Genre.create(tmdb_genre_id: 12, name: "Adventure")
    Genre.create(tmdb_genre_id: 16, name: "Animation")
    Genre.create(tmdb_genre_id: 35, name: "Comedy")
    Genre.create(tmdb_genre_id: 80, name: "Crime")
    Genre.create(tmdb_genre_id: 99, name: "Documentary")
    Genre.create(tmdb_genre_id: 18, name: "Drama")
    Genre.create(tmdb_genre_id: 10751, name: "Family")
    Genre.create(tmdb_genre_id: 14, name: "Fantasy")
    Genre.create(tmdb_genre_id: 36, name: "History")
    Genre.create(tmdb_genre_id: 27, name: "Horror")
	Genre.create(tmdb_genre_id: 10762, name: "Kids")
    Genre.create(tmdb_genre_id: 10402, name: "Music")
    Genre.create(tmdb_genre_id: 9648, name: "Mystery")
	Genre.create(tmdb_genre_id: 10763, name: "News")
	Genre.create(tmdb_genre_id: 10764, name: "Reality")
    Genre.create(tmdb_genre_id: 10749, name: "Romance")
    Genre.create(tmdb_genre_id: 878, name: "Science Fiction")
	Genre.create(tmdb_genre_id: 10765, name: "Sci-Fi & Fantasy")
	Genre.create(tmdb_genre_id: 10766, name: "Soap")
	Genre.create(tmdb_genre_id: 10767, name: "Talk")
    Genre.create(tmdb_genre_id: 10770, name: "TV Movie")
    Genre.create(tmdb_genre_id: 53, name: "Thriller")
    Genre.create(tmdb_genre_id: 10752, name: "War")
	Genre.create(tmdb_genre_id: 10768, name: "War & Politics")
    Genre.create(tmdb_genre_id: 37, name: "Western")